<?php

/**
 * Plugin Name: Slider Carousel
 * Author: Xavier Arbour
 * Description: Affiche le carrousel associé à la galerie wordpress
 * Version: 1.0
 * Plugin URI: 
 * Author URI: httsp://referenced.ca.
 * 
 */

function xa_enqueue_slider_style_script() {
    // Enqueue CSS
    wp_enqueue_style(
        'xa_plugin_slider_css',
        plugin_dir_url(__FILE__) . "css/slider-style.css",
        array(),
        '1.0.0'
    );

    // Enqueue JS
    wp_enqueue_script(
        'xa_plugin_slider_js',
        plugin_dir_url(__FILE__) . "js/slider-car.js",
        array('jquery'),
        '1.0.0',
        true
    );

    // Initialize the image URLs array
    $image_urls = array();

    // Get images from the "Acceuil" page
    $page = get_page_by_path('acceuil');
    if ($page) {
        $images = get_attached_media('image', $page->ID);

        foreach ($images as $image) {
            $image_urls[] = wp_get_attachment_url($image->ID);
        }
    } else {
        error_log('Page "Acceuil" not found.');
    }

    // Pass image URLs to JavaScript
    wp_localize_script('xa_plugin_slider_js', 'carouselImages', array('images' => $image_urls));
}

// Add scripts and styles in the header/footer
add_action('wp_enqueue_scripts', 'xa_enqueue_slider_style_script');

// Define the shortcode function
function slider_car_shortcode() {
    // Return an empty string as the HTML is generated by JavaScript
    return '<div class="cible-carousel"></div>';
}

// Register the shortcode
add_shortcode('slider_car', 'slider_car_shortcode');
?>