<?php

/**
 * Plugin Name: Slider Carousel
 * Author: Xavier Arbour
 * Description: Affiche le carrousel 2D associé à la galerie wordpress
 * Version: 1.0
 * Plugin URI: 
 * Author URI: httsp://referenced.ca.
 * 
 */

function xa_enqueue_slider_style_script() {
    // Regarde si la page actuelle est la page "Profs"
    if (is_page('Profs')) {
        // Enqueue CSS
        wp_enqueue_style(
            'xa_plugin_slider_css',
            plugin_dir_url(__FILE__) . "css/slider-style.css",
            array(),
            '1.0.0'
        );

        // Enqueue JS
        wp_enqueue_script(
            'xa_plugin_slider_js',
            plugin_dir_url(__FILE__) . "js/slider-car.js",
            array('jquery'),
            '1.0.0',
            true
        );

        // Initialisation d'un array pour les URLs des images
        $image_urls = array();

        // Obtenir les images de la page "Profs"
        $page = get_page_by_path('Profs');
        if ($page) {
            $images = get_attached_media('image', $page->ID);

            foreach ($images as $image) {
                $image_urls[] = wp_get_attachment_url($image->ID);
            }
        } else {
            error_log('Page "Profs" not found.');
        }

        // Passation des images au script JS du carousel
        wp_localize_script('xa_plugin_slider_js', 'carouselData', array(
            'images' => $image_urls,
            'pageSlug' => 'Profs'
        ));
    }
}

// Ajout des scripts et styles au header/ footer de la page
add_action('wp_enqueue_scripts', 'xa_enqueue_slider_style_script');

// Définir le shortcode
function slider_car_shortcode() {
    // Return an empty string as the HTML is generated by JavaScript
    return '<div class="cible-carousel"></div>';
}

// Enregistrer le shortcode
add_shortcode('slider_car', 'slider_car_shortcode');
?>